---
- name: Let's encrypt Ansible ACME example
  hosts: localhost

  tasks:
    - name: Set acme_domain
      ansible.builtin.set_fact:
        acme_domain:  "tomasek.cz"
        acme_web_dir: "/var/www/tomasek.cz"

    - name: Generate private key
      community.crypto.openssl_privatekey:
        path: "tmp/{{ acme_domain }}.key"
        type: RSA
        size: 2048
        mode: 0600

    - name: Generate certificate signing request (CSR)
      openssl_csr:
        path: "tmp/{{ acme_domain }}.csr"
        privatekey_path: "tmp/{{ acme_domain }}.key"
        common_name: "{{ acme_domain }}"
        subject_alt_name: "DNS:www.{{ acme_domain }},DNS:{{ acme_domain }}"
        mode: 0600

    - name: Create a challenge
      community.crypto.acme_certificate:
        account_key_src: "tmp/{{ acme_domain }}.key"
        account_email: jan@tomasek.cz
        csr: "tmp/{{ acme_domain }}.csr"
        dest: "tmp/{{ acme_domain }}}.crt"
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        acme_version: 2
        terms_agreed: true
      register: acme_challenge

    - name: Show challenge
      debug: var=acme_challenge

    - name: Copy HTTP-01 challenge data
      copy:
        dest: "{{ acme_web_dir }}/{{ item.value['http-01']['resource'] }}"
        content: "{{ item.value['http-01']['resource_value'] }}"
      with_dict:
        - "{{ acme_challenge['challenge_data'] }}"

    - name: Let the challenge be validated and retrieve the cert and intermediate certificate
      community.crypto.acme_certificate:
        account_key_src: "tmp/{{ acme_domain }}.key"
        csr: "tmp/{{ acme_domain }}.csr"
        dest: "tmp/{{ acme_domain }}.crt"
        fullchain_dest: "tmp/{{ acme_domain }}.-fullchain.crt"
        chain_dest: "tmp/{{ acme_domain }}.-intermediate.crt"
        data: "{{ acme_challenge }}"
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        acme_version: 2
        terms_agreed: true

#    - name: Show challenge data2
#      debug: msg={{ acme_challenge['challenge_data']["{{ acme_domain }}"] }}

    # - name: Copy HTTP-01 challenge data
    #   copy:
    #     dest: /var/www/html/{{ acme_challenge['challenge_data']["{{ acme_domain }}"]['http-01']['resource'] }}
    #     content: {{ acme_challenge['challenge_data']["{{ acme_domain }}"]['http-01']['resource_value'] }}
    #     when: acme_challenge is changed and "{{ acme_domain }}" in acme_challenge['challenge_data']
